name: Trigger release

on:
  workflow_dispatch:
    inputs:
      commit:
        description: 'Commit SHA to check out and release'
        required: false
        default: master
        type: string
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 20
    if: ${{ github.repository == 'flathub-infra/flatpak-builder-lint' && github.ref == 'refs/heads/master' }}

    steps:
      # 6.0.2
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0
          persist-credentials: false
          ref: ${{ inputs.commit }}

      - name: Trigger workflow in org.flatpak.Builder repository
        # 4.0.1
        uses: peter-evans/repository-dispatch@28959ce8df70de7be546dd1250a005dd32156697
        with:
          repository: flathub/org.flatpak.Builder
          event-type: trigger-workflow
          client-payload: "{\"sha\": \"${{ inputs.commit }}\"}"
          token: ${{ secrets.LINTER_TRIGGER_WORKFLOW_TOKEN }}

      - name: Trigger workflow in flathub-infra/actions-images
        # 4.0.1
        uses: peter-evans/repository-dispatch@28959ce8df70de7be546dd1250a005dd32156697
        with:
          repository: flathub-infra/actions-images
          event-type: trigger-workflow
          token: ${{ secrets.LINTER_TRIGGER_WORKFLOW_TOKEN }}
